name: dsci532


channels:
  - conda-forge

dependencies:
  - python>=3.11,<3.12
  - pip

  # Data Handling
  - pandas>=2.0
  - numpy>=1.24

  # Visualization
  - plotly>=5.18
  - altair>=5.0

  # Dashboard
  - shiny>=0.7
  - shinywidgets>=0.2

  # Development
  - jupyterlab>=4.0
  - ipykernel>=6.25

  - pip:
      - kaggle>=1.6